rename BASEDIR to LSQ_BASEDIR

diff --git a/lsq b/lsq
--- a/lsq
+++ b/lsq
@@ -9,12 +9,17 @@ fi
 
 # Check them variables
 failed=0
-for var in query BASEDIR PORT TIMEOUT MONITORS; do
+for var in query LSQ_BASEDIR PORT TIMEOUT MONITORS; do
     if [[ -z "$(eval echo \$$var)" ]]; then
         echo "ERROR: no $var provided!"
         failed=1
     fi
 done
+
+if [[ $LSQ_BASEDIR =~ ^.*[\ ].*$ ]]; then
+    echo "ERROR: Do not use an LSQ_BASEDIR with spaces in it!"
+    exit 1
+fi
 
 if [[ $failed -eq 1 ]]; then
     exit 1
@@ -22,9 +27,9 @@ fi
 
 
 # Let's export $qfile to make it availble to any of the $query.pre scripts
-export qfile="$BASEDIR/queries/$query.lql"
-pre_qfile="$BASEDIR/queries/$query.pre"
-post_qfile="$BASEDIR/queries/$query.post"
+export qfile="$LSQ_BASEDIR/queries/$query.lql"
+pre_qfile="$LSQ_BASEDIR/queries/$query.pre"
+post_qfile="$LSQ_BASEDIR/queries/$query.post"
 
 if [[ ! -f $qfile ]] ; then
     echo "Query file for $query not found!"
@@ -44,21 +49,22 @@ else
     query_text=$(cat $qfile)
 fi
 
+[[ -d $LSQ_BASEDIR/tmp ]] || mkdir "$LSQ_BASEDIR/tmp"
 for monitor in ${MONITORS[@]}; do
-    outfile="$BASEDIR/tmp/$monitor.$$"
-    nc -w$TIMEOUT $monitor $PORT < <(echo "$query_text") > "$outfile" \
+    outfile="$LSQ_BASEDIR/tmp/$monitor.$$"
+    nc -w$TIMEOUT $monitor $PORT < <(echo "$query_text") > $outfile \
         || echo "ERROR: Failed to query monitor: $monitor" 1>&2 &
 done
 wait
 
-cmd="cat ${BASEDIR}/tmp/*.$$"
+cmd="cat $LSQ_BASEDIR/tmp/*.$$"
 
 
 if [[ -x $post_qfile ]]; then
     cmd=$cmd"| $post_qfile"
-elif [[ -x $BASEDIR/queries/default.post ]]; then
-    cmd="$cmd | \"$BASEDIR/queries/default.post\""
+elif [[ -x $LSQ_BASEDIR/queries/default.post ]]; then
+    cmd="$cmd | \"$LSQ_BASEDIR/queries/default.post\""
 fi
 
 eval "$cmd"
-rm ${BASEDIR}/tmp/*.$$
+rm $LSQ_BASEDIR/tmp/*.$$
